### ISSUE TITLE
Mobile About Us and Services Page 

### ISSUE THREAD

**Issue by LKoech** [olivernjeru/ist4035-project-1-group-2#16]
Working on this

**Comment by olivernjeru** [comment]
I suggest splitting these two issues into serparate issues and tackle one at a time while comming and pushing the code into their respective branches. Alternatively, if you think you can handle both at the same time without breaking the codebase, then, I am looking forward to reviewing the pull request.

**Comment by olivernjeru** [comment]
The pull request related to this issue has been merged hence this issue will be closed.
